name: CD

on:
  workflow_call:

env:
  CLUSTER: skillpulse
  NAMESPACE: skillpulse
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  EC2_HOST: ${{ secrets.EC2_HOST }}

jobs:
  deploy:
    if: ${{ vars.DEPLOY_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: CLUSTER,NAMESPACE,DOCKERHUB_USERNAME,MYSQL_ROOT_PASSWORD,DB_PASSWORD,DB_HOST,DB_PORT,DB_USER,DB_NAME
          script: |
            set -e # Exit immediately if any command fails
            echo "Install required package"
            sudo apt update -y
            sudo apt install docker.io -y
            sudo apt install docker-compose-v2 -y
            sudo usermod -aG docker $USER && newgrp docker

            # Ensure kubectl is installed on the target machine
            if ! command -v kubectl &> /dev/null; then
              echo "Installing kubectl binary directly..."
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
              echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
              sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
              # Clean up temporary verification files to keep the workspace immaculate
              rm -f kubectl kubectl.sha256
              kubectl version --client
            fi

            # ensure kind is installed
            if ! command -v kind &> /dev/null; then
              echo "Downloading and installing Kind..."
              [ $(uname -m) = x86_64 ] && ARCH=amd64 || ARCH=arm64
              curl -fsSL -o ./kind "https://k8s.io{ARCH}"
              chmod +x ./kind
              sudo mv ./kind /usr/local/bin/kind
              kind version
            fi

            # Fetch updated manifests
            if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
            fi
            cd ~/github-actions-kubernetes-masterclass
            git pull origin main

            # GENERATE THE .ENV FILE
            echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > .env
            echo "DB_HOST=$MDB_HOST" >> .env
            echo "DB_PORT=$DB_PORT" >> .env
            echo "DB_USER=$DB_USER" >> .env 
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env 
            echo "DB_NAME=$DB_NAME" >> .env 
            echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" >> .env 

            if [ ! -f .env ]; then
              echo "ERROR: ~/github-actions-kubernetes-masterclass/.env is missing. Create it once with DOCKERHUB_USERNAME and DB credentials."
              exit 1
            fi
            
            # Create a cluster ' if none exist
            if ! kind get clusters | grep -q "^${CLUSTER}$"; then
              echo "No active Kind cluster found. Creating one..."
              kind create cluster --config k8s/kind-config.yaml --name "${CLUSTER}"
            fi

            # cretae namespace 
            kubectl apply -f k8s/00-namespace.yaml

            # Deploy observability stack
            # Convert your raw files into Kubernetes ConfigMaps
            kubectl create configmap prometheus-config --from-file=monitoring/prometheus.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap alert-rules --from-file=monitoring/alert-rules.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap loki-config --from-file=monitoring/loki/loki-config.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap promtail-config --from-file=monitoring/promtail/promtail-config.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap otel-config --from-file=monitoring/otel-collector/otel-collector-config.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
          
            # Grafana Provisioning ConfigMaps
            kubectl create configmap grafana-datasources --from-file=monitoring/grafana/provisioning/datasources/datasources.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -
            kubectl create configmap grafana-dashboards --from-file=monitoring/grafana/provisioning/dashboards/dashboards.yml -n "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

            # Apply your Pod deployment manifests
            kubectl apply -f k8s/monitoring-deployments.yml -n "${NAMESPACE}"

            # Deploying to Kind Cluster
            echo "==== 5. Deploying to Cluster ===="
            kubectl apply -f k8s/10-mysql.yaml
            kubectl apply -f k8s/20-backend.yaml
            kubectl apply -f k8s/30-frontend.yaml

            echo "==== 6. Verifying Service Rollouts ===="
            kubectl rollout status statefulset/mysql    -n "${NAMESPACE}" --timeout=180s
            kubectl rollout status deployment/backend   -n "${NAMESPACE}" --timeout=120s
            kubectl rollout status deployment/frontend  -n "${NAMESPACE}" --timeout=60s
            
            # Open below Links to open WEB APP and Grafana Dashboard
            echo "===================================================================="
            echo " DEPLOYMENT SUCCESSFUL!"
            echo "Open URL http://${{ secrets.EC2_HOST }}:8888 to access your application"
            echo "Open URL http://${{ secrets.EC2_HOST }}:3000 to access the Grafana dashboard"
            echo "Open URL http://${{ secrets.EC2_HOST }}:9090 to access the prometheus dashboard"
            echo "===================================================================="