name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'k8s/**'
      - 'docs/**'
      - '**/*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # validate backend dockerfile
      - name: validate backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: ./backend/Dockerfile
          ignore: DL3018 
        
      # validate frontend dockerfile
      - name: validate frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with: 
          dockerfile: ./frontend/Dockerfile

      - uses: docker/setup-buildx-action@v4
      # build backend and frontend image
      - name: Build backend Docker Image
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.sha }} ./backend
          fi
      - name: Build Frontend docker image
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.sha }} ./frontend
          fi
      # backend image scan
      - name: backend Trivy Scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit code: '1'
          trivyignore: ${{ github.workspace }}/.
      # frontend image scan
      - name: frontend Trivy Scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit code: '1'
          trivyignore: ${{ github.workspace }}/.trivyignore
      # login and push image 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ vars.DEPLOY_ENABLED == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag & push scanned image to dockerhub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.sha }}
          docker image tag ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-frontend:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.sha }}
          docker image tag ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillpulse-backend:latest
